services:

  nestjs:
    build: .
    ports:
      - 3001:3000
    volumes:
      - .:/home/node/app
    networks:
      - gateway-api_default
    
  nestjs-db:
    image: postgres:17.4
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb
    ports:
      - 5433:5432
    networks:
      - gateway-api_default
      
networks:
  gateway-api_default:
    external: true