services:
  gateway_db:
    image: postgres:17.4
    container_name: gateway_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: gateway
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  gateway_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway_api
    environment:
      DATABASE_URL: postgres://postgres:postgres@gateway_db:5432/gateway
    ports:
      - "3000:3000"
    depends_on:
      gateway_db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local