services:
  gateway_db:
    image: postgres:17.4
    container_name: gateway_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: gateway
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  gateway_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway_api
    environment:
      HTTP_PORT: 8080
      DB_NAME: gateway
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: gateway_db
      DB_PORT: 5432
      DB_SSL_MODE: disable
    ports:
      - "8080:8080"
    depends_on:
      gateway_db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local